# Generated by Django 5.2.12 on 2026-08-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_achievement_portfolio_a_is_acti_6559dc_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['slug', 'is_active', 'is_draft'], name='portfolio_a_slug_e1985d_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_type', 'slug'], name='portfolio_c_categor_6802f7_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['is_read', 'created_at'], name='portfolio_c_is_read_62b04a_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['slug', 'is_active', 'is_draft'], name='portfolio_e_slug_13b117_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug', 'is_active'], name='portfolio_p_slug_ee4c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active', 'views'], name='portfolio_p_is_acti_e537ae_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['slug', 'is_active', 'is_draft'], name='portfolio_s_slug_8cbd75_idx'),
        ),
    ]
